// qr.test.mjs — the QR encoder's falsifiers.
//
// WHY GOLDEN VECTORS AND NOT A LIBRARY: a QR that encodes the wrong bytes is
// worse than no QR — it misdirects real money while looking authoritative. So
// the matrices below were generated by src/lib/qr.mjs and then CROSS-CHECKED,
// before being frozen here, two independent ways:
//   1. decoded with jsQR (an independent decoder) back to the exact input, and
//   2. diffed against the `qrcode` package's own reference encoder, which
//      decodes to the same string.
// Neither library is a dependency of this site — they were used once, in a
// scratch directory, to earn these fixtures. To re-earn them after any change
// to the encoder, repeat that: `npm i jsqr qrcode` somewhere disposable, render
// this module's matrix to a bitmap, and assert jsQR reads the input back.
//
// THE BUG THIS CAUGHT, recorded because it is the reason the fixtures exist:
// the first encoder built its Reed-Solomon generator polynomial in ascending
// degree order and fed it to a division loop that expects descending. Every ECC
// byte was wrong, every symbol was unreadable, and NOTHING about the output
// looked wrong — the finder patterns, the timing, the version and the format
// bits were all correct. Only a decoder could tell.

import test from "node:test";
import assert from "node:assert/strict";
import { qrMatrix, qrSvg, pickVersion } from "../src/lib/qr.mjs";

// Frozen output, verified by decode at the moment of capture (see the header).
const GOLDEN = {
  A: {
    text: "A",
    rows: [
      "111111101001001111111",
      "100000101111101000001",
      "101110100010101011101",
      "101110101101101011101",
      "101110100111001011101",
      "100000100101101000001",
      "111111101010101111111",
      "000000001101100000000",
      "101101110011101001011",
      "010110010101111001000",
      "110011101101000001101",
      "101101000001001111100",
      "100111100100100100100",
      "000000001011001001001",
      "111111101001100101000",
      "100000101100000110110",
      "101110100110111110001",
      "101110101111001111110",
      "101110101010101100000",
      "100000100010010100101",
      "111111101000010010000",
    ],
  },
  intake: {
    text: "0x2a273b0e5D0648DfF9B9ED7a4A5041E6762b8C78",
    rows: [
      "11111110000100100010101111111",
      "10000010000001010000101000001",
      "10111010111110001000001011101",
      "10111010110011111001101011101",
      "10111010100100000011001011101",
      "10000010110101011000001000001",
      "11111110101010101010101111111",
      "00000000101010001011000000000",
      "10111110010111011110001111100",
      "11010100001011100000101010011",
      "01000010111010010100110011000",
      "01000000000110001000010110011",
      "11001011001110111101110011110",
      "10001101110000000011001110001",
      "10100011010101011010000110110",
      "01111001000000111001111110010",
      "10110111100011010110010101111",
      "10100101010110111000101011001",
      "10111110000001111000000111100",
      "10101101001010110011110110010",
      "10111111010001011000111111110",
      "00000000101101100010100010001",
      "11111110011100010011101011110",
      "10000010110110011001100011011",
      "10111010100010011110111110111",
      "10111010100010000000010000011",
      "10111010101010010001001110110",
      "10000010011000010000011010010",
      "11111110110010111111010011100",
    ],
  },};

test("the encoder reproduces its verified output, module for module", () => {
  for (const [name, g] of Object.entries(GOLDEN)) {
    const m = qrMatrix(g.text).map((r) => r.map((v) => (v ? "1" : "0")).join(""));
    assert.equal(m.length, g.rows.length, `${name}: wrong symbol size`);
    assert.deepEqual(m, g.rows, `${name}: the matrix drifted from the decoded-verified fixture`);
  }
});

test("THE INTAKE ADDRESS is the payload, character for character", () => {
  // The one that matters. A QR on a money page that encodes anything other than
  // the published intake address sends a patron's USDC somewhere else, with no
  // appeal. The fixture's text is asserted against the address the office
  // publishes, so a typo in either one goes red here.
  assert.equal(GOLDEN.intake.text, "0x2a273b0e5D0648DfF9B9ED7a4A5041E6762b8C78");
  assert.equal(GOLDEN.intake.text.length, 42, "an EVM address is 0x + 40 hex characters");
  assert.match(GOLDEN.intake.text, /^0x[0-9a-fA-F]{40}$/);
});

test("the symbol carries its quiet zone — the thing hand-rolled QRs drop", () => {
  // The spec's 4-module quiet zone is what lets a scanner FIND the symbol.
  // Trimming it to look tidier is the classic reason a QR "sometimes" fails.
  const svg = qrSvg("0x2a273b0e5D0648DfF9B9ED7a4A5041E6762b8C78", { size: 200 });
  const n = qrMatrix("0x2a273b0e5D0648DfF9B9ED7a4A5041E6762b8C78").length;
  assert.match(svg, new RegExp(`viewBox="0 0 ${n + 8} ${n + 8}"`), "4 modules of quiet on every side");
  assert.match(svg, /shape-rendering="crispEdges"/, "no anti-aliasing between modules");
  assert.ok(!/https?:/.test(svg.replace(/xmlns="[^"]*"/, "")), "no external anything — the CSP would block it and a money page is the wrong place to learn that");
});

test("versions are chosen by capacity, and the ceiling refuses rather than truncates", () => {
  // Silently dropping characters past the ceiling would encode a TRUNCATED
  // address, which is the same failure mode as encoding the wrong one.
  assert.equal(pickVersion(14), 1);
  assert.equal(pickVersion(15), 2);
  assert.equal(pickVersion(42), 3, "an EVM address fits version 3 at level M exactly");
  assert.throws(() => pickVersion(214), /past this encoder's ceiling/);
  assert.throws(() => qrMatrix("z".repeat(500)), /past this encoder's ceiling/);
});

test("the SVG is deterministic — the same address renders the same markup", () => {
  const a = qrSvg("0x2a273b0e5D0648DfF9B9ED7a4A5041E6762b8C78");
  const b = qrSvg("0x2a273b0e5D0648DfF9B9ED7a4A5041E6762b8C78");
  assert.equal(a, b, "a money surface that renders differently build to build is not auditable");
});
